export const DQL_KEYWORDS = [
  "SELECT",
  "FROM",
  "WHERE",
  "AND",
  "OR",
  "NOT",
  "LIKE",
  "IN",
  "IS",
  "NULL",
  "BETWEEN",
  "ORDER",
  "BY",
  "ENABLE",
  "RETURN_TOP",
  "FTDQL",
  "FOLDER",
  "CABINET",
  "TYPE",
  "ANY",
  "UPDATE",
  "OBJECTS",
  "SET",
  "DELETE",
  "CREATE",
  "GROUP",
  "HAVING",
  "UNION",
  "ALL",
  "DISTINCT",
  "ASC",
  "DESC",
  "DESCEND",
  "SYNONYM",
  "INSERT",
  "INTO",
  "VALUES",
  "TRUE",
  "FALSE",
  "AS",
];

export const DQL_FUNCTIONS = [
  "COUNT",
  "SUM",
  "AVG",
  "MIN",
  "MAX",
  "DATE",
  "DATETIME",
  "DATETOSTRING",
  "UPPER",
  "LOWER",
  "SUBSTR",
  "SUBSTRING",
  "LENGTH",
  "USER",
  "TODAY",
  "NOW",
  "YESTERDAY",
];

export function registerDql(monaco: typeof import("monaco-editor")) {
  monaco.languages.register({ id: "dql" });
  monaco.languages.setLanguageConfiguration("dql", {
    comments: { lineComment: "--", blockComment: ["/*", "*/"] },
    brackets: [
      ["(", ")"],
    ],
    autoClosingPairs: [
      { open: "(", close: ")" },
      { open: "'", close: "'" },
    ],
    surroundingPairs: [
      { open: "(", close: ")" },
      { open: "'", close: "'" },
    ],
    wordPattern: /[a-zA-Z_][\w]*/,
  });
  monaco.languages.setMonarchTokensProvider("dql", {
    ignoreCase: true,
    defaultToken: "",
    keywords: DQL_KEYWORDS,
    builtin: DQL_FUNCTIONS,
    operators: ["=", "<>", "!=", "<", ">", "<=", ">="],
    tokenizer: {
      root: [
        [/--.*$/, "comment"],
        [/\/\*/, "comment", "@comment"],
        [/'([^']|'')*'/, "string"],
        [/'([^']|'')*$/, "string.invalid"],
        [/[0-9]+(\.[0-9]+)?/, "number"],
        [/<>|!=|<=|>=|[=<>]/, "operator"],
        [/[()*,.]/, "delimiter"],
        [
          /[a-zA-Z_][\w]*/,
          { cases: { "@keywords": "keyword", "@builtin": "predefined", "@default": "identifier" } },
        ],
      ],
      comment: [
        [/\*\//, "comment", "@pop"],
        [/./, "comment"],
      ],
    },
  });
}
