server:
  port: 18080

spring:
  application:
    name: ECM-Dev-Workbench
  web:
    resources:
      cache:
        cachecontrol:
          max-age: 86400

workbench:
  home: ${user.home}/.ecm-dev-workbench
  desktop: false
  open-browser: false

logging:
  file:
    name: ${workbench.home}/logs/workbench.log
